export interface Satellite {
  id: string;
  name: string;
  country: string;
  countryFlag: string;
  agency: string;
  launchDate: string;
  launchVehicle: string;
  orbitType: "LEO" | "MEO" | "GEO" | "HEO" | "Interplanetary";
  altitudeKm: number;
  status: "Active" | "Inactive" | "Deorbited" | "Lost" | "Graveyard Orbit";
  missionType: "Science" | "Military" | "Communication" | "Navigation" | "Weather" | "Commercial" | "Crewed";
  costUSD?: string;
  description: string;
  facts: string[];
  imageUrl?: string;
}

export const satellites: Satellite[] = [
  {
    id: "hubble",
    name: "Hubble Space Telescope",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA / ESA",
    launchDate: "1990-04-24",
    launchVehicle: "Space Shuttle Discovery (STS-31)",
    orbitType: "LEO",
    altitudeKm: 547,
    status: "Active",
    missionType: "Science",
    costUSD: "$4.7B (lifetime)",
    description:
      "The Hubble Space Telescope is one of the largest and most versatile space telescopes ever built, renowned for producing deep-field images of the universe and revolutionizing our understanding of cosmology, galaxy formation, and the age of the universe.",
    facts: [
      "Has made over 1.5 million observations since 1990",
      "Traveled more than 4 billion miles in orbit",
      "Has observed objects as distant as 13.4 billion light-years away",
      "Underwent 5 servicing missions by Space Shuttle crews",
      "Provided evidence for the accelerating expansion of the universe",
    ],
  },
  {
    id: "iss",
    name: "International Space Station",
    country: "Multinational",
    countryFlag: "🌍",
    agency: "NASA / Roscosmos / ESA / JAXA / CSA",
    launchDate: "1998-11-20",
    launchVehicle: "Proton-K (first module)",
    orbitType: "LEO",
    altitudeKm: 408,
    status: "Active",
    missionType: "Crewed",
    costUSD: "$150B+",
    description:
      "The International Space Station is a modular space station in low Earth orbit. It is the largest human-made structure in space and has been continuously occupied since November 2000, serving as a laboratory for microgravity research.",
    facts: [
      "Orbits Earth approximately every 92 minutes",
      "Visible to the naked eye from Earth's surface",
      "Has hosted over 270 astronauts from 20 countries",
      "Spans the area of a football field (109m)",
      "Planned for deorbit around 2030",
    ],
  },
  {
    id: "sputnik-1",
    name: "Sputnik 1",
    country: "USSR",
    countryFlag: "🇷🇺",
    agency: "Roscosmos (Soviet Program)",
    launchDate: "1957-10-04",
    launchVehicle: "Sputnik 8K71PS",
    orbitType: "LEO",
    altitudeKm: 250,
    status: "Deorbited",
    missionType: "Science",
    description:
      "Sputnik 1 was the first artificial Earth satellite, launched by the Soviet Union. Its launch marked the beginning of the Space Age and triggered the Space Race between the USA and USSR. It transmitted radio pulses for 21 days before its batteries died.",
    facts: [
      "First artificial satellite to orbit Earth",
      "Orbited for 3 months before re-entering the atmosphere",
      "Weighed only 83.6 kg",
      "Transmitted a simple radio beep signal on 20.005 and 40.002 MHz",
      "Sparked the creation of NASA and the US space program",
    ],
  },
  {
    id: "sputnik-2",
    name: "Sputnik 2 (Laika)",
    country: "USSR",
    countryFlag: "🇷🇺",
    agency: "Soviet Space Program",
    launchDate: "1957-11-03",
    launchVehicle: "Sputnik 8K71PS",
    orbitType: "LEO",
    altitudeKm: 212,
    status: "Deorbited",
    missionType: "Science",
    description:
      "Sputnik 2 carried Laika, the first living creature to orbit Earth. The mission proved that living organisms could survive in space, though Laika died from overheating hours into the mission. The satellite re-entered in April 1958.",
    facts: [
      "Carried Laika, the first animal in orbit",
      "Laika was a stray dog found on Moscow streets",
      "Had no recovery system — Laika could not return",
      "Paved the way for human spaceflight",
      "Re-entered and burned up in April 1958",
    ],
  },
  {
    id: "vanguard-1",
    name: "Vanguard 1",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "US Navy / NRL",
    launchDate: "1958-03-17",
    launchVehicle: "Vanguard",
    orbitType: "MEO",
    altitudeKm: 3750,
    status: "Inactive",
    missionType: "Science",
    description:
      "Vanguard 1 is the oldest man-made object still in orbit around Earth. Despite being nicknamed 'The Grapefruit' by Soviet premier Khrushchev for its tiny size (16.5cm), it provided the first evidence of Earth's slight pear shape.",
    facts: [
      "Oldest human-made object still in space",
      "Weighs only 1.47 kg — smallest satellite ever launched",
      "Proved Earth is slightly pear-shaped (oblate spheroid)",
      "Expected to remain in orbit for another 200+ years",
      "Nicknamed 'The Grapefruit' by Khrushchev",
    ],
  },
  {
    id: "starlink",
    name: "Starlink Constellation",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "SpaceX",
    launchDate: "2019-05-23",
    launchVehicle: "Falcon 9",
    orbitType: "LEO",
    altitudeKm: 550,
    status: "Active",
    missionType: "Communication",
    costUSD: "$10B+ (estimated)",
    description:
      "Starlink is SpaceX's mega-constellation of broadband internet satellites. With over 6,000 satellites in operation, it is by far the largest satellite constellation in history, providing internet access globally including in remote regions.",
    facts: [
      "Largest satellite constellation ever built (6,000+)",
      "Plans to deploy up to 42,000 satellites",
      "Provides internet speeds of 50–500 Mbps",
      "Has raised concerns about light pollution for astronomers",
      "Generated $1.4B in revenue in 2023",
    ],
  },
  {
    id: "gps-block-iii",
    name: "GPS Block III",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "US Space Force / Lockheed Martin",
    launchDate: "2018-12-23",
    launchVehicle: "Falcon 9",
    orbitType: "MEO",
    altitudeKm: 20200,
    status: "Active",
    missionType: "Navigation",
    costUSD: "$500M per satellite",
    description:
      "GPS Block III satellites are the latest generation of the Global Positioning System, providing three times more accurate positioning than previous generations and featuring an anti-jam capability eight times better than earlier GPS satellites.",
    facts: [
      "3x more accurate than earlier GPS generations",
      "8x more anti-jam resistant",
      "First GPS satellites to include L1C signal for international compatibility",
      "Designed to operate for 15 years",
      "10 Block III satellites planned",
    ],
  },
  {
    id: "chandrayaan-2",
    name: "Chandrayaan-2 Orbiter",
    country: "India",
    countryFlag: "🇮🇳",
    agency: "ISRO",
    launchDate: "2019-07-22",
    launchVehicle: "GSLV Mark III",
    orbitType: "HEO",
    altitudeKm: 100,
    status: "Active",
    missionType: "Science",
    costUSD: "$140M",
    description:
      "Chandrayaan-2 is India's second lunar exploration mission. While the Vikram lander crashed during touchdown, the orbiter has been successfully mapping the Moon's surface with its suite of 8 scientific instruments.",
    facts: [
      "Orbiter continues to function perfectly despite lander crash",
      "Carries 8 scientific instruments",
      "Mapped water ice in lunar permanently shadowed regions",
      "Cost only $140M — one of cheapest lunar orbiters",
      "Expected to operate until 2025",
    ],
  },
  {
    id: "mangalyaan",
    name: "Mangalyaan (MOM)",
    country: "India",
    countryFlag: "🇮🇳",
    agency: "ISRO",
    launchDate: "2013-11-05",
    launchVehicle: "PSLV-XL C25",
    orbitType: "Interplanetary",
    altitudeKm: 421,
    status: "Inactive",
    missionType: "Science",
    costUSD: "$74M",
    description:
      "India's Mars Orbiter Mission (Mangalyaan) was India's first interplanetary mission. It made India the first country to reach Mars orbit on its maiden attempt and the fourth space agency to do so. The mission cost less than the Hollywood film Gravity.",
    facts: [
      "First Mars mission to succeed on debut attempt",
      "India's first interplanetary mission",
      "Cheaper than the movie 'Gravity' ($74M vs $100M)",
      "Operated for 7+ years — planned for 6 months",
      "Lost contact in September 2022",
    ],
  },
  {
    id: "jwst",
    name: "James Webb Space Telescope",
    country: "USA/International",
    countryFlag: "🇺🇸",
    agency: "NASA / ESA / CSA",
    launchDate: "2021-12-25",
    launchVehicle: "Ariane 5",
    orbitType: "HEO",
    altitudeKm: 1500000,
    status: "Active",
    missionType: "Science",
    costUSD: "$10B",
    description:
      "The James Webb Space Telescope is the most powerful space telescope ever built, observing the universe in infrared light. It can see objects 100 times fainter than Hubble and has already produced groundbreaking images of distant galaxies, exoplanet atmospheres, and star-forming regions.",
    facts: [
      "Orbits the Sun at Lagrange Point 2, 1.5 million km from Earth",
      "Primary mirror is 6.5m across — 7x the area of Hubble",
      "Can detect heat from a bumblebee at the Moon's distance",
      "Operates at -233°C (colder than deep space on sunlit side)",
      "Has imaged galaxies from just 300 million years after the Big Bang",
    ],
  },
  {
    id: "chandra",
    name: "Chandra X-ray Observatory",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA",
    launchDate: "1999-07-23",
    launchVehicle: "Space Shuttle Columbia (STS-93)",
    orbitType: "HEO",
    altitudeKm: 139000,
    status: "Active",
    missionType: "Science",
    costUSD: "$1.65B",
    description:
      "Chandra X-ray Observatory studies high-energy phenomena in the universe including black holes, supernovas, galaxy clusters, and dark matter. It is one of NASA's Great Observatories and has produced transformative discoveries about the hot, energetic universe.",
    facts: [
      "Detects X-ray emission from hot plasma at millions of degrees",
      "Orbit takes it 1/3 of the way to the Moon",
      "Has been operating for 25+ years — triple its design life",
      "Discovered evidence of dark energy",
      "Named after Indian-American astrophysicist Subrahmanyan Chandrasekhar",
    ],
  },
  {
    id: "voyager-1",
    name: "Voyager 1",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA / JPL",
    launchDate: "1977-09-05",
    launchVehicle: "Titan IIIE",
    orbitType: "Interplanetary",
    altitudeKm: 24000000000,
    status: "Active",
    missionType: "Science",
    costUSD: "$865M",
    description:
      "Voyager 1 is the most distant human-made object in existence, now in interstellar space. Launched in 1977, it conducted flybys of Jupiter and Saturn before escaping the solar system. It carries the Golden Record — a message to any intelligent life that might find it.",
    facts: [
      "Most distant human-made object ever — 24+ billion km from Earth",
      "First spacecraft to cross the heliopause into interstellar space",
      "Still communicating with Earth after 47+ years",
      "Signal takes 22+ hours to reach Earth at the speed of light",
      "Carries the Golden Record with sounds and images of Earth",
    ],
  },
  {
    id: "voyager-2",
    name: "Voyager 2",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA / JPL",
    launchDate: "1977-08-20",
    launchVehicle: "Titan IIIE",
    orbitType: "Interplanetary",
    altitudeKm: 19800000000,
    status: "Active",
    missionType: "Science",
    costUSD: "$865M",
    description:
      "Voyager 2 is the only spacecraft to have visited all four outer planets — Jupiter, Saturn, Uranus, and Neptune. It is now in interstellar space and continues to transmit scientific data about the outer heliosphere.",
    facts: [
      "Only probe to visit Uranus and Neptune",
      "Discovered active volcanoes on Jupiter's moon Io",
      "Found Neptune's moon Triton has nitrogen geysers",
      "Also in interstellar space, but not as far as Voyager 1",
      "Has enough power to operate until ~2026",
    ],
  },
  {
    id: "goes-18",
    name: "GOES-18",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NOAA / NASA",
    launchDate: "2022-03-01",
    launchVehicle: "Atlas V",
    orbitType: "GEO",
    altitudeKm: 35786,
    status: "Active",
    missionType: "Weather",
    costUSD: "$1B",
    description:
      "GOES-18 (also known as GOES-West) provides weather imagery and soundings of Western United States, Pacific Ocean, and Hawaii. It is part of NOAA's GOES-R series, featuring the most advanced weather instrumentation ever deployed in geostationary orbit.",
    facts: [
      "Images full disk of Earth every 5 minutes",
      "16-channel Advanced Baseline Imager (ABI)",
      "First GOES satellite with lightning mapper over Pacific",
      "Provides data for 7-day weather forecasts",
      "Located at 136.7°W longitude",
    ],
  },
  {
    id: "landsat-9",
    name: "Landsat 9",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA / USGS",
    launchDate: "2021-09-27",
    launchVehicle: "Atlas V",
    orbitType: "LEO",
    altitudeKm: 705,
    status: "Active",
    missionType: "Science",
    costUSD: "$750M",
    description:
      "Landsat 9 continues the world's longest-running land imaging program, providing continuous multispectral imagery of Earth's surface since 1972. It monitors deforestation, agricultural changes, urban growth, glacial retreat, and natural disasters.",
    facts: [
      "Images entire Earth every 16 days",
      "11-band multispectral scanner including thermal infrared",
      "15m to 100m spatial resolution depending on band",
      "Data is free and publicly available",
      "Partners with Landsat 8 for 8-day revisit cycle",
    ],
  },
  {
    id: "sentinel-6",
    name: "Sentinel-6 Michael Freilich",
    country: "Europe/USA",
    countryFlag: "🇪🇺",
    agency: "ESA / EUMETSAT / Copernicus",
    launchDate: "2020-11-21",
    launchVehicle: "Falcon 9",
    orbitType: "LEO",
    altitudeKm: 1336,
    status: "Active",
    missionType: "Science",
    costUSD: "$900M",
    description:
      "Sentinel-6 is the most accurate sea-level monitoring satellite ever launched, measuring global ocean surface topography with millimeter precision. It continues a 30-year sea-level measurement record and is critical for tracking climate change.",
    facts: [
      "Most precise sea-level altimeter ever",
      "Accuracy to within a few centimeters",
      "Named after NASA oceanographer Michael Freilich",
      "Orbits 1,336 km altitude with 10-day repeat cycle",
      "Key climate change monitoring satellite",
    ],
  },
  {
    id: "tiangong-css",
    name: "Tiangong Space Station (CSS)",
    country: "China",
    countryFlag: "🇨🇳",
    agency: "CNSA",
    launchDate: "2021-04-29",
    launchVehicle: "Long March 5B",
    orbitType: "LEO",
    altitudeKm: 390,
    status: "Active",
    missionType: "Crewed",
    costUSD: "$10B (estimated)",
    description:
      "The Chinese Space Station (CSS/Tiangong) is China's permanent modular space station, constructed between 2021 and 2022. It serves as China's national laboratory in space and can accommodate up to 6 taikonauts simultaneously.",
    facts: [
      "China's first permanent space station",
      "Three-module configuration: Tianhe, Wentian, Mengtian",
      "Planned operational life of 10–15 years",
      "Features a 25m robotic arm for assembly tasks",
      "Closed to all non-Chinese astronauts due to US political restrictions",
    ],
  },
  {
    id: "mir",
    name: "Mir Space Station",
    country: "USSR/Russia",
    countryFlag: "🇷🇺",
    agency: "Roscosmos",
    launchDate: "1986-02-19",
    launchVehicle: "Proton-K",
    orbitType: "LEO",
    altitudeKm: 386,
    status: "Deorbited",
    missionType: "Crewed",
    costUSD: "$4.3B",
    description:
      "Mir was the Soviet Union's (later Russia's) iconic space station, operating from 1986 to 2001. It was the first continuously inhabited long-term research station in space and set multiple endurance records. It was deliberately deorbited into the South Pacific.",
    facts: [
      "Operated for 15 years — far beyond its 5-year design life",
      "Hosted 125 cosmonauts and astronauts from 12 countries",
      "Site of the Mir collision accident in 1997",
      "Cosmonaut Valeri Polyakov spent 437 days on Mir — longest spaceflight",
      "Splashed down in South Pacific on March 23, 2001",
    ],
  },
  {
    id: "skylab",
    name: "Skylab",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA",
    launchDate: "1973-05-14",
    launchVehicle: "Saturn V",
    orbitType: "LEO",
    altitudeKm: 435,
    status: "Deorbited",
    missionType: "Crewed",
    costUSD: "$2.2B",
    description:
      "Skylab was America's first space station. Launched in 1973, it hosted three crews and conducted extensive solar astronomy, biomedical research, and Earth observation. Without a reboost mission, it re-entered Earth's atmosphere in 1979, with debris landing in western Australia.",
    facts: [
      "First American space station",
      "Hosted 3 crews totaling 171 days of habitation",
      "Debris landed in Esperance, Australia in 1979",
      "NASA was fined $400 by Esperance for 'littering'",
      "Solar telescope produced 150,000 images of the Sun",
    ],
  },
  {
    id: "kosmos-954",
    name: "Kosmos-954",
    country: "USSR",
    countryFlag: "🇷🇺",
    agency: "Soviet Military",
    launchDate: "1977-09-18",
    launchVehicle: "Tsyklon-2",
    orbitType: "LEO",
    altitudeKm: 250,
    status: "Deorbited",
    missionType: "Military",
    description:
      "Kosmos-954 was a Soviet RORSAT (Radar Ocean Reconnaissance Satellite) powered by a nuclear reactor with 50kg of enriched uranium. When it unexpectedly re-entered the atmosphere in January 1978, radioactive debris was scattered across 600km of Canadian territory.",
    facts: [
      "Crashed over Canada in January 1978",
      "Scattered radioactive uranium debris over 600km of Northwest Territories",
      "Only nuclear satellite to crash on foreign territory",
      "Led to Operation Morning Light — largest nuclear search in history",
      "Canada billed USSR $6M for cleanup (settled for $3M)",
    ],
  },
  {
    id: "uars",
    name: "UARS (Upper Atmosphere Research Satellite)",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA",
    launchDate: "1991-09-15",
    launchVehicle: "Space Shuttle Discovery (STS-48)",
    orbitType: "LEO",
    altitudeKm: 600,
    status: "Deorbited",
    missionType: "Science",
    costUSD: "$740M",
    description:
      "UARS was NASA's Upper Atmosphere Research Satellite that studied ozone depletion and other atmospheric chemistry for 14 years. Its uncontrolled re-entry in 2011 sparked widespread media coverage about 'deadly space debris' — though all pieces landed in the ocean.",
    facts: [
      "Weighed 5,900 kg — one of the largest uncontrolled reentries",
      "Up to 26 metal fragments survived reentry",
      "Media predicted 1-in-3,200 odds of hitting a person",
      "Debris fell into the Pacific Ocean harmlessly",
      "Provided key ozone layer depletion data",
    ],
  },
  {
    id: "iridium-next",
    name: "Iridium NEXT",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "Iridium Communications / SpaceX",
    launchDate: "2017-01-14",
    launchVehicle: "Falcon 9",
    orbitType: "LEO",
    altitudeKm: 780,
    status: "Active",
    missionType: "Communication",
    costUSD: "$3B",
    description:
      "Iridium NEXT replaced the original Iridium constellation with 66 second-generation satellites, providing global satellite phone coverage with no dead zones anywhere on Earth. SpaceX launched all 75 satellites (66 operational + 9 spares) in just 7 Falcon 9 launches.",
    facts: [
      "66 satellites provide 100% global coverage including poles",
      "Only network that covers both poles",
      "Each satellite communicates with 4 others via crosslinks",
      "Also host Aireon ADS-B aviation tracking service",
      "All deployed by SpaceX Falcon 9 in 2017-2019",
    ],
  },
  {
    id: "oneweb",
    name: "OneWeb Constellation",
    country: "UK",
    countryFlag: "🇬🇧",
    agency: "OneWeb / Eutelsat",
    launchDate: "2019-02-27",
    launchVehicle: "Soyuz / Ariane 6",
    orbitType: "LEO",
    altitudeKm: 1200,
    status: "Active",
    missionType: "Communication",
    costUSD: "$6B+",
    description:
      "OneWeb is a broadband internet constellation of 648 satellites in low Earth orbit, providing global internet coverage. After going bankrupt in 2020, it was acquired by the UK government and Bharti Global, and merged with Eutelsat in 2023.",
    facts: [
      "648 satellites in 1,200km LEO orbit",
      "Went bankrupt in March 2020 during COVID-19",
      "UK government became a major shareholder post-bankruptcy",
      "Merged with French operator Eutelsat in 2023",
      "Provides connectivity to hard-to-reach regions",
    ],
  },
  {
    id: "planet-labs",
    name: "Planet Labs Dove",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "Planet Labs",
    launchDate: "2013-01-09",
    launchVehicle: "Various (Antares, Falcon 9, ISS deploy)",
    orbitType: "LEO",
    altitudeKm: 475,
    status: "Active",
    missionType: "Commercial",
    costUSD: "$100M+",
    description:
      "Planet Labs operates the world's largest fleet of Earth-imaging satellites — over 200 tiny 3U CubeSats called Doves. The constellation can image the entire Earth's landmass every single day, providing unprecedented monitoring capability for agriculture, deforestation, and conflict tracking.",
    facts: [
      "Images entire Earth landmass every day",
      "200+ tiny 3U CubeSat satellites",
      "3–5m resolution imagery",
      "Used for tracking deforestation, crop health, and military activity",
      "Has imaged over 3 billion km² of Earth's surface",
    ],
  },
  {
    id: "beidou-g7",
    name: "BeiDou-3 G7",
    country: "China",
    countryFlag: "🇨🇳",
    agency: "CNSA",
    launchDate: "2020-06-23",
    launchVehicle: "Long March 3B",
    orbitType: "GEO",
    altitudeKm: 35786,
    status: "Active",
    missionType: "Navigation",
    costUSD: "$300M+ per satellite",
    description:
      "BeiDou-3 G7 was the final satellite in China's BeiDou Navigation Satellite System (BDS), completing the constellation. BeiDou provides positioning, navigation, and timing services globally, rivaling GPS, GLONASS, and Galileo.",
    facts: [
      "Final satellite to complete the BeiDou-3 constellation",
      "35-satellite constellation provides global coverage",
      "Provides accuracy of 1.5–3m worldwide",
      "2.5 million users in China rely on BeiDou",
      "Launched on Chinese National Day (June 23) for symbolic timing",
    ],
  },
  {
    id: "galileo-iov1",
    name: "Galileo IOV-1",
    country: "Europe",
    countryFlag: "🇪🇺",
    agency: "ESA / GSA",
    launchDate: "2011-10-21",
    launchVehicle: "Soyuz-ST",
    orbitType: "MEO",
    altitudeKm: 23222,
    status: "Active",
    missionType: "Navigation",
    costUSD: "$11B (program total)",
    description:
      "Galileo IOV-1 (In-Orbit Validation 1) was the first Galileo satellite, marking Europe's first step toward an independent satellite navigation system. Galileo provides positioning independent of US GPS and Russian GLONASS, ensuring European strategic autonomy.",
    facts: [
      "First satellite in Europe's Galileo GNSS constellation",
      "Provides 20cm accuracy to authorized users",
      "4x more accurate than basic GPS",
      "36-satellite constellation covers entire globe",
      "Provides Search and Rescue services globally",
    ],
  },
  {
    id: "new-horizons",
    name: "New Horizons",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA / APL / SwRI",
    launchDate: "2006-01-19",
    launchVehicle: "Atlas V",
    orbitType: "Interplanetary",
    altitudeKm: 7000000000,
    status: "Active",
    missionType: "Science",
    costUSD: "$700M",
    description:
      "New Horizons is the first spacecraft to visit Pluto and the Kuiper Belt. In 2015, it captured humanity's first close-up images of Pluto, revealing a geologically active world with mountains, plains, and possible liquid water beneath its surface.",
    facts: [
      "First spacecraft to visit Pluto (July 2015)",
      "Revealed Pluto has mountains, glaciers, and a heart-shaped plain",
      "Flew past Arrokoth — most distant object ever visited by spacecraft",
      "Fastest spacecraft at launch — 58,536 km/h",
      "Still operating in the Kuiper Belt",
    ],
  },
  {
    id: "cassini",
    name: "Cassini-Huygens",
    country: "USA/Europe",
    countryFlag: "🇺🇸",
    agency: "NASA / ESA / ASI",
    launchDate: "1997-10-15",
    launchVehicle: "Titan IVB/Centaur",
    orbitType: "Interplanetary",
    altitudeKm: 0,
    status: "Deorbited",
    missionType: "Science",
    costUSD: "$3.26B",
    description:
      "Cassini-Huygens was one of the most ambitious and successful space missions ever attempted. It orbited Saturn for 13 years, discovering six new moons, exploring the complex ring system, and deploying the Huygens probe onto Saturn's moon Titan.",
    facts: [
      "Orbited Saturn for 13 years (2004–2017)",
      "Discovered water vapor geysers on Enceladus",
      "Deployed Huygens probe — first landing on Titan",
      "Discovered 6 new moons of Saturn",
      "Intentionally crashed into Saturn in 'Grand Finale' to protect moons",
    ],
  },
  {
    id: "noaa-21",
    name: "NOAA-21",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NOAA / NASA",
    launchDate: "2022-11-10",
    launchVehicle: "Atlas V",
    orbitType: "LEO",
    altitudeKm: 833,
    status: "Active",
    missionType: "Weather",
    costUSD: "$1.5B (program)",
    description:
      "NOAA-21 (also known as JPSS-2) is the second operational satellite in NOAA's Joint Polar Satellite System, providing polar-orbiting weather data for 7-day global weather forecasts, storm tracking, and climate monitoring.",
    facts: [
      "Polar sun-synchronous orbit covering entire globe twice daily",
      "5 science instruments including advanced infrared sounder",
      "Provides 7-day weather forecast data",
      "Key data source for hurricane intensity forecasts",
      "15-year operational design life",
    ],
  },
  {
    id: "terra",
    name: "Terra",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA",
    launchDate: "1999-12-18",
    launchVehicle: "Atlas IIAS",
    orbitType: "LEO",
    altitudeKm: 705,
    status: "Active",
    missionType: "Science",
    costUSD: "$1.3B",
    description:
      "Terra is NASA's flagship Earth Observing System satellite, carrying five instruments to monitor Earth's land, oceans, and atmosphere simultaneously. It provides foundational data on climate change, fires, aerosol pollution, and vegetation health.",
    facts: [
      "Carries MODIS — most-used Earth science instrument ever",
      "Operating for 25+ years — triple its design life",
      "Provides daily global fire maps",
      "Monitors sea surface temperature, cloud cover, and ice extent",
      "Part of Earth Observing System constellation with Aqua",
    ],
  },
  {
    id: "aqua",
    name: "Aqua",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA",
    launchDate: "2002-05-04",
    launchVehicle: "Delta II",
    orbitType: "LEO",
    altitudeKm: 705,
    status: "Active",
    missionType: "Science",
    costUSD: "$952M",
    description:
      "Aqua is NASA's Earth Observing System satellite focused on water in all its forms — water vapor, sea surface temperature, precipitation, and sea ice. Along with Terra, it forms the cornerstone of NASA's Earth monitoring fleet.",
    facts: [
      "Named 'Aqua' for water-focused science mission",
      "6 Earth-observing instruments onboard",
      "MODIS instrument images entire Earth every 1–2 days",
      "Tracks Arctic and Antarctic sea ice extent in real time",
      "Over 20 years of continuous operation",
    ],
  },
  {
    id: "fermi",
    name: "Fermi Gamma-ray Space Telescope",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "NASA / DOE",
    launchDate: "2008-06-11",
    launchVehicle: "Delta II Heavy",
    orbitType: "LEO",
    altitudeKm: 550,
    status: "Active",
    missionType: "Science",
    costUSD: "$690M",
    description:
      "The Fermi Gamma-ray Space Telescope detects the highest-energy form of light in the universe. It has catalogued over 6,000 gamma-ray sources including pulsars, supernova remnants, active galactic nuclei, and gamma-ray bursts.",
    facts: [
      "Detects gamma rays — highest energy photons in the universe",
      "Catalogued 6,000+ gamma-ray sources",
      "Discovered hundreds of new pulsars",
      "Observed thousands of gamma-ray bursts",
      "Key instrument for dark matter searches",
    ],
  },
  {
    id: "glonass-m",
    name: "GLONASS-M",
    country: "Russia",
    countryFlag: "🇷🇺",
    agency: "Roscosmos / Russian Aerospace Forces",
    launchDate: "2003-12-10",
    launchVehicle: "Proton-M",
    orbitType: "MEO",
    altitudeKm: 19140,
    status: "Active",
    missionType: "Navigation",
    costUSD: "$100M per satellite",
    description:
      "GLONASS-M satellites form the backbone of Russia's Global Navigation Satellite System (GLONASS), providing positioning and timing services. GLONASS is the only GPS alternative with global coverage, maintained to provide Russia strategic independence from US GPS.",
    facts: [
      "Russia's answer to US GPS",
      "24-satellite constellation covers entire globe",
      "Frequency-division multiple access (vs. GPS code-division)",
      "Accuracy of 2.8m globally",
      "Historically degraded without adequate funding — now fully operational",
    ],
  },
  {
    id: "insat-3d",
    name: "INSAT-3D",
    country: "India",
    countryFlag: "🇮🇳",
    agency: "ISRO / IMD",
    launchDate: "2013-07-26",
    launchVehicle: "Ariane 5",
    orbitType: "GEO",
    altitudeKm: 35786,
    status: "Active",
    missionType: "Weather",
    costUSD: "$250M",
    description:
      "INSAT-3D is an advanced meteorological satellite by ISRO, equipped with a 6-channel imager and 19-channel sounder for weather monitoring over the Indian subcontinent and Indian Ocean region. It plays a key role in cyclone tracking and monsoon forecasting.",
    facts: [
      "Provides 30-minute full-disk imagery of South Asia",
      "Monitors monsoon patterns over Indian Ocean",
      "Key for Bay of Bengal cyclone early warning",
      "Data relay transponder for disaster warning systems",
      "Search and Rescue transponder covers Indian Ocean",
    ],
  },
  {
    id: "gsat-11",
    name: "GSAT-11",
    country: "India",
    countryFlag: "🇮🇳",
    agency: "ISRO",
    launchDate: "2018-12-05",
    launchVehicle: "Ariane 5",
    orbitType: "GEO",
    altitudeKm: 35786,
    status: "Active",
    missionType: "Communication",
    costUSD: "$200M",
    description:
      "GSAT-11 is India's heaviest and most advanced communication satellite, providing Ka and Ku band broadband connectivity across India. It is India's first high-throughput satellite with a capacity of over 16 Gbps.",
    facts: [
      "India's heaviest satellite at 5,854 kg",
      "16+ Gbps total communication capacity",
      "32 user beams covering entire India",
      "Provides broadband internet to remote regions",
      "Named India's 'satellite of the decade'",
    ],
  },
  {
    id: "himawari-9",
    name: "Himawari-9",
    country: "Japan",
    countryFlag: "🇯🇵",
    agency: "JMA / JAXA",
    launchDate: "2016-11-02",
    launchVehicle: "H-IIA",
    orbitType: "GEO",
    altitudeKm: 35786,
    status: "Active",
    missionType: "Weather",
    costUSD: "$270M",
    description:
      "Himawari-9 is Japan's geostationary meteorological satellite monitoring the Asia-Pacific region. Standing by as backup to Himawari-8, it features a 16-band Advanced Himawari Imager that produces stunning full-disk images of Earth every 10 minutes.",
    facts: [
      "Monitors typhoons, climate, and aviation hazards over Asia-Pacific",
      "16-band imager covers visible and infrared spectrum",
      "Produces full-disk images every 10 minutes",
      "Currently in standby mode (Himawari-8 is operational)",
      "Expected to become operational around 2029",
    ],
  },
  {
    id: "meteosat-12",
    name: "Meteosat-12 (MTG-I1)",
    country: "Europe",
    countryFlag: "🇪🇺",
    agency: "EUMETSAT / ESA",
    launchDate: "2022-12-13",
    launchVehicle: "Ariane 5",
    orbitType: "GEO",
    altitudeKm: 35786,
    status: "Active",
    missionType: "Weather",
    costUSD: "$3.4B (MTG program)",
    description:
      "Meteosat Third Generation Imager-1 (MTG-I1) is Europe's latest and most advanced geostationary weather satellite, featuring a 16-band Flexible Combined Imager and the first Lightning Imager over Europe. It transforms European weather forecasting capability.",
    facts: [
      "First satellite in the Meteosat Third Generation series",
      "First Lightning Imager over Europe — real-time storm tracking",
      "16-band imager for unprecedented weather detail",
      "Products 10x higher resolution than previous generation",
      "Planned 8.5-year operational life",
    ],
  },
  {
    id: "vanguard-tv3",
    name: "Vanguard TV3",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "US Navy / NRL",
    launchDate: "1957-12-06",
    launchVehicle: "Vanguard",
    orbitType: "LEO",
    altitudeKm: 0,
    status: "Lost",
    missionType: "Science",
    description:
      "Vanguard TV3 was America's disastrous first attempt to launch a satellite, exploding on the launch pad just 2 seconds after ignition, reaching only 1.2m altitude. The global humiliation — broadcast live on TV — accelerated the creation of NASA and pushed the US to urgently develop Explorer 1.",
    facts: [
      "America's most embarrassing launch failure",
      "Exploded 2 seconds after ignition",
      "Broadcast live on national television",
      "Soviet press called it 'Kaputnik' and 'Flopnik'",
      "Its failure directly accelerated NASA's formation",
    ],
  },
  {
    id: "o3b-mpower",
    name: "O3b mPower",
    country: "Luxembourg/USA",
    countryFlag: "🇱🇺",
    agency: "SES Networks",
    launchDate: "2022-12-16",
    launchVehicle: "Falcon 9",
    orbitType: "MEO",
    altitudeKm: 8062,
    status: "Active",
    missionType: "Communication",
    costUSD: "$3.5B",
    description:
      "O3b mPower is SES's second-generation MEO broadband constellation, providing fiber-like internet speeds of 10 Gbps or more to maritime, aviation, government, and enterprise customers worldwide from medium Earth orbit.",
    facts: [
      "Provides 10+ Gbps throughput to individual customers",
      "MEO orbit gives lower latency than GEO",
      "Serves ships, islands, and remote enterprise customers",
      "Software-defined satellites can redirect beams in real time",
      "Teamed with SpaceX for all launches",
    ],
  },
  {
    id: "iridium-cosmos-collision",
    name: "Iridium 33 (Collision Debris)",
    country: "USA",
    countryFlag: "🇺🇸",
    agency: "Iridium Communications",
    launchDate: "1997-09-14",
    launchVehicle: "Proton",
    orbitType: "LEO",
    altitudeKm: 789,
    status: "Lost",
    missionType: "Communication",
    description:
      "Iridium 33 was an operational Iridium satellite that was destroyed in the world's first accidental hypervelocity collision in orbit, when it collided with the defunct Russian Kosmos-2251 satellite on February 10, 2009. The collision created over 2,000 trackable debris fragments.",
    facts: [
      "First accidental collision of two intact satellites in history",
      "Collided with Kosmos-2251 at ~11 km/s",
      "Created 2,000+ trackable debris pieces",
      "Debris threatened ISS and other satellites for decades",
      "Neither satellite had collision avoidance capability",
    ],
  },
];

export function getSatelliteById(id: string): Satellite | undefined {
  return satellites.find((s) => s.id === id);
}

export function searchSatellites(
  query: string,
  filters: {
    status?: string;
    orbitType?: string;
    country?: string;
    missionType?: string;
  } = {}
): Satellite[] {
  let results = satellites;

  if (query) {
    const q = query.toLowerCase();
    results = results.filter(
      (s) =>
        s.name.toLowerCase().includes(q) ||
        s.agency.toLowerCase().includes(q) ||
        s.country.toLowerCase().includes(q) ||
        s.description.toLowerCase().includes(q)
    );
  }

  if (filters.status && filters.status !== "All") {
    results = results.filter((s) => s.status === filters.status);
  }

  if (filters.orbitType && filters.orbitType !== "All") {
    results = results.filter((s) => s.orbitType === filters.orbitType);
  }

  if (filters.country && filters.country !== "All") {
    results = results.filter((s) => s.country === filters.country);
  }

  if (filters.missionType && filters.missionType !== "All") {
    results = results.filter((s) => s.missionType === filters.missionType);
  }

  return results;
}

export const graveyardSatellites = satellites.filter(
  (s) => s.status === "Deorbited" || s.status === "Lost" || s.status === "Inactive"
);
